config/routes.rb
Rails.application.routes.draw do
  get "mypage" => "users#show"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'static_pages#top'

  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_header.html.erb
<header class="bg-gray-50">
  <div class="max-w-full mx-auto px-8 py-4 flex items-center justify-between">
    
    <!-- ロゴリンク（左寄せ） -->
    <div class="text-xl font-semibold text-gray-800">
      <%= link_to 'とくろぐ', user_signed_in? ? posts_path : root_path, class: 'hover:text-blue-600 transition' %>
    </div>

    <!-- ナビゲーション（右寄せ） -->
    <nav class="flex space-x-2 text-sm">
      <% if user_signed_in? %>
        <%= link_to "徳を積む", new_post_path,
          class: "px-3 py-2 text-blue-600 bg-gray-100 rounded-lg hover:shadow hover:text-blue-700 transition" %>
        <%= link_to 'マイページ', mypage_path,
              class: 'px-3 py-2 text-gray-700 bg-gray-100 rounded-lg hover:shadow hover:text-gray-900 transition' %>
        <%= button_to 'サインアウト', destroy_user_session_path, method: :delete,
          class: 'px-3 py-2 text-red-600 bg-gray-100 rounded-lg hover:shadow hover:text-red-700 transition' %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path,
              class: 'px-3 py-2 text-blue-600 bg-gray-100 rounded-lg hover:shadow hover:text-blue-700 transition' %>
        <%= link_to 'サインイン', new_user_session_path,
              class: 'px-3 py-2 text-gray-700 bg-gray-100 rounded-lg hover:shadow hover:text-gray-900 transition' %>
      <% end %>
    </nav>

  </div>
</header>